# Generated by Django 3.1.7 on 2021-03-27 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=200)),
                ('from_location', models.CharField(max_length=200)),
                ('to_location', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('duration', models.CharField(max_length=200)),
                ('v_class', models.CharField(max_length=200)),
                ('v_type', models.CharField(choices=[['Car', 'Car'], ['Bus', 'Bus'], ['Train', 'Train'], ['Flight', 'Flight']], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=300)),
                ('lname', models.CharField(max_length=300)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=300)),
                ('gender', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('class_type', models.CharField(max_length=100)),
                ('v_type', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('book_date', models.DateTimeField(auto_now_add=True)),
                ('gst', models.IntegerField(default=0)),
                ('total', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
